# Generated by Django 5.2.1 on 2025-06-03 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height_in', models.PositiveIntegerField(blank=True, help_text='Height in inches', null=True)),
                ('weight_lb', models.PositiveIntegerField(blank=True, help_text='Weight in pounds', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('wet', 'Wet'), ('dirty', 'Dirty'), ('both', 'Both')], max_length=10)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('allgone', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('bottle', 'Bottle'), ('breast', 'Breast'), ('solid', 'Solid')], max_length=50)),
                ('amount_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.baby')),
            ],
        ),
    ]
