# Generated by Django 5.2.1 on 2025-06-04 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaper',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
