# Generated by Django 5.2.1 on 2025-06-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_diaper_time_alter_feeding_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='allgone',
        ),
    ]
