# Generated by Django 5.2.1 on 2025-06-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_feeding_allgone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='weight_lb',
            field=models.FloatField(blank=True, help_text='Weight in pounds', null=True),
        ),
    ]
