# Generated by Django 5.2.1 on 2025-06-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_baby_photo_baby_user_appointment_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
