# Generated by Django 5.2.1 on 2025-06-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='breast_used',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='solid_food_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
