# Generated by Django 5.2.1 on 2025-06-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_feeding_breast_used_feeding_solid_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='amount_ml',
            new_name='amount_oz',
        ),
    ]
