# Generated by Django 5.2.1 on 2025-06-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_amount_ml_feeding_amount_oz'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
