# Generated by Django 5.2.1 on 2025-06-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_appointment_latitude_appointment_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
